### ISSUE TITLE
Trying to scan

### ISSUE THREAD

**Issue by sp90** [clarkie/dynogels#105]
Okay so i want to query by some values

``` javascript
Messages
  .scan()
  .startKey(lastKey)
  .limit(10)
  .where('message_subject_internal').contains(query)
  .exec(callback);
```

Lets say `query` is empty shouldn't the framework just not add the filter query that way i dont have to do all the cases in my route

Otherwise i can end up with some serious spagetti code?

**Comment by cdhowie** [comment]
You shouldn't need spaghetti code...

```js
let scan = Messages
  .scan()
  .startKey(lastKey)
  .limit(10);

if (query && query.length) {
  scan = scan.where('message_subject_internal').contains(query);
}

scan.exec(callback);
```

This seems perfectly readable to me, and is a fairly standard way to conditionally build queries/scans.

**Comment by sp90** [comment]
Thanks 👍
