### ISSUE TITLE
When the limit is the same from the table rows total number

### ISSUE THREAD

**Issue by ricardodantas** [clarkie/dynogels#106]
Hi folks,

I'm facing this situation: If limit has the same number from the table rows it returns the **LastEvaluatedKey** parameter.

Is this a Dynogels bug or a DynamoDB behavior?

Thanks in advanced.

**Comment by cdhowie** [comment]
[Dynogels doesn't touch this parameter on the way through](https://github.com/clarkie/dynogels/blob/master/lib/table.js#L490). It comes straight from DynamoDB. Nothing we can do about it without making an extra query/scan call to see if there are any more rows.
