### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by jerep6** [clarkie/dynogels#117]
Hi,

Given the number of pull requests / issues unanswered and the date of the last release, I wonder if the project is still maintained.

Do you have more information?

**Comment by clarkie** [comment]
Hi @jerep6 ,

Yes, I try and stay on top of this and have recently brought @dangerginger and @cdhowie on board to help out. I'm hoping to get a release out this week of things that we've merged recently. 

Is there a particular issue you're after an update on?

Thanks

Clarkie

**Comment by jerep6** [comment]
Good news! :)

For now, no particular issue for me.

I asked the question because the state of the issues is not reassuring. The answer is either "submit to PR" or no answer.

See no criticism, I imagine the difficulty it is to maintain a project of this magnitude.

**Comment by clarkie** [comment]
See also https://github.com/ryanfitz/vogels/issues/171 to give you an idea of the history of this module. 

> I asked the question because the state of the issues is not reassuring. The answer is either "submit to PR" or no answer.
Unfortunately, when I suggest people raise a PR it never happens. Should I close those issues?
