### ISSUE TITLE
set created and updatedat to epoch

### ISSUE THREAD

**Issue by Alphatiger** [clarkie/dynogels#126]
when timestamps options is true, there should be an option to set the timestamp to epoch, instead of only ISO string

**Comment by clarkie** [comment]
Hi @Alphatiger, thanks for the suggestion but can you explain what problem you have storing them as ISO strings? Thanks, Clarkie

**Comment by Alphatiger** [comment]
when backends doesn't support date operations e.g dynamodb we can fall back to epoch based comparison.

**Comment by clarkie** [comment]
I've always found the `2018-01-03` format much better as often people ask for reports between two dates and it's much easier to reason about `date >= '2017-12-01' && date <= '2017-12-31'`.

**Comment by Alphatiger** [comment]
As i mentioned above the dynamodb doesnt allow any date operations, we have to fallback to epoch for this purpose, so ideally give an option for timestamp to be epoch or ISO string.
this should be an option available at table declaration itself

**Comment by clarkie** [comment]
But dynamodb doesn't need any date operations. You can use string operations for the comparisons as I showed above. 

![image](https://user-images.githubusercontent.com/2292639/34516724-ed6f3556-f06f-11e7-95d0-9a25ac92aafc.png)

**Comment by Alphatiger** [comment]
Hi Thanks

my primary tested showed this is working, can you please tell me does dynamodb compare this as per their ascii values or how it compares?

**Comment by cdhowie** [comment]
The comparison is lexicographic. One of the advantages of ISO-8601-formatted dates is that they can be compared lexicographically, since more significant date components always appear to the left of less significant date components.

**Comment by clarkie** [comment]
@Alphatiger yes, dynamodb does compare using ascii values:

> String value comparisons for greater than, equals, or less than are based on ASCII character code values. For example, a is greater than A, and a is greater than B. For a list of code values, see http://en.wikipedia.org/wiki/ASCII#ASCII_printable_characters.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html

I'm closing this as I think we have resolved your issue. 

Thanks, Clarkie
