### ISSUE TITLE
aws-sdk version could use updating (Security)

### ISSUE THREAD

**Issue by iDVB** [clarkie/dynogels#130]
Apparently `aws-sdk` `<2.178.0` has a potential vulnerability that is now fixed in `>=2.178.0`.

https://snyk.io/test/npm/dynogels/8.0.1?severity=high&severity=medium&severity=low

![image](https://user-images.githubusercontent.com/189506/34737239-95d24fd0-f543-11e7-836f-882b680557bb.png)

**Comment by cdhowie** [comment]
Isn't this module only actually used when bundled for a browser?  Dynogels is not designed to run in a browser -- you're typically not performing database operations from the frontend.

**Comment by iDVB** [comment]
@cdhowie your likely correct. However, that dep currently and validly fires off read flags for [Snyk.io](https://snyk.io/test/npm/dynogels/8.0.1?severity=high&severity=medium&severity=low) and the version of `aws-sdk` that `dynogels` currently uses could simply be updated to even just `v2.178.0` (not latest) and would still correct the issue.

Shouldn't `aws-sdk` be a peer dependency anyway? Or since the version differences are only `minor` aren't the chances high that this would be an non-breaking change to `dynogels`?

**Comment by cdhowie** [comment]
Closing this as a duplicate of #148, which has a subtask of updating dependencies to satisfy bitHound (which checks for vulnerabilities).
