### ISSUE TITLE
paginated requests

### ISSUE THREAD

**Issue by cdelgadob** [clarkie/dynogels#132]
I need to make an infinite scroll in my UI, and for that I plan to use cursors inqueries to dynamodb

I have been diving into the code and saw that there's a `paginatedRequest` method in `utils.js`, which I couldn't find in the documentation - see [here](https://github.com/clarkie/dynogels/blob/6fc96c8b75fc125da0dd503f55f4c79fb3af6ee3/lib/utils.js)

Would this method work for request where I can set a cursos and a number of records to retrieve or should I use the [low-level dynamodb](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html?shortFooter=true#Query.Pagination) API to achieve this?

Thanks in advance

 Carlos

**Comment by cdhowie** [comment]
You can use `.query(...).limit(n)` to limit the results to `n` objects.  If there is possibly more data beyond the limited results, the returned data will include an `ExclusiveStartKey` attribute, which you can pass to the `.startKey()` query method.  See [the query documentation](https://github.com/clarkie/dynogels#query).
