### ISSUE TITLE
Unable to query using only the rangeKey.

### ISSUE THREAD

**Issue by shishiranshuman13** [clarkie/dynogels#137]
I just started working on DynamoDB so please forgive me if the following seems silly.

* I have a model with a `hashKey` and a `rangeKey`. Let's name these as HASH and RANGE respectively.
* A global secondary index: `GlobalIndex` is added to the model as well.

Now what I want is to get the list of records by `rangeKey`. I don't want to use the `scan` operation since it impacts the performance. I am unable to achieve this with the `query` operation. 
Trying to achieve something like [this](https://stackoverflow.com/a/38814345/5284640) with dynogels.

Any kind of help would be really helpful to me.

Thanks.

Dynogels: 9.0.0
Node: 6.10.3

**Comment by cdhowie** [comment]
You cannot query on only the range key.  Does your global secondary index use your table's range key as its hash key?

**Comment by shishiranshuman13** [comment]
Sure. Here is the model I am using:

```
dynogels.define('user-address', {
    hashKey : 'user_id',
    rangeKey: 'location',

    timestamps : true,

    schema : {
        location: Joi.string(),
        pin: Joi.number(),
        user_id: Joi.string()
    },

    indexes: [{
        hashKey: 'user_id',
        rangeKey: 'location',
        name: 'AddressGlobalIndex',
        type: 'global',
    }],
});
```

**Comment by cdhowie** [comment]
Your index has the same hash key and range key as your table. This is entirely redundant.

**Comment by shishiranshuman13** [comment]
Yes, you are right. Fixed it. It was a dumb mistake. Thanx a lot for the help. ✌️
