### ISSUE TITLE
in serverless , I can defines the permission policy for the Lambda function. but if I want to use dynogels I have to give to secret key for init  (Security)

### ISSUE THREAD

**Issue by Wolke** [clarkie/dynogels#142]
as tilte.

**Comment by Wolke** [comment]
do not have any bug in Lambda function , 
but give up the best security way what AWS give to lambda.

**Comment by cdhowie** [comment]
@Wolke I'm not sure I understand the question.  IAM roles are the standard way to give permissions to a Lambda function.
