### ISSUE TITLE
Example project code

### ISSUE THREAD

**Issue by jameslee89** [clarkie/dynogels#151]
Are there any examples where dynogels is used in a serverless project? 
Or could someone point me in the right direction on how to properly use dynogels in function calls, and setting up tables in a project.

**Comment by cdhowie** [comment]
Use dynogels in function calls just like you use it elsewhere.

As far as setting up tables, generally what people do is have a Lambda function specifically for creating tables, and invoke it as part of the CI process that deploys new code to Lambda.
