### ISSUE TITLE
Old lodash version shows a low severity vulnerability with npm audit

### ISSUE THREAD

**Issue by ktchernov** [clarkie/dynogels#157]
When using npm version >6, there is a low level security errors when running `npm audit`,  caused by using an old version of lodash: https://nodesecurity.io/advisories/577  

Simply fixed by bumping lodash version.

PR: https://github.com/clarkie/dynogels/pull/155

**Comment by cdhowie** [comment]
Closing this as a duplicate of #148, which has a subtask of updating dependencies to satisfy bitHound (which checks for vulnerabilities).
