### ISSUE TITLE
What is the syntax for getItems with a composite primary key?

### ISSUE THREAD

**Issue by aneilbaboo** [clarkie/dynogels#161]
The documentation only shows an example like `Model.getItems(["hashkey1", "hashkey2"], ...`. The AWS documentation indicates that for a table with a composite primary key you must pass both the hash and rangeKey.  

Does Dynogels accept an array of arrays like this?
```js
Model.getItems([['hk1', 'rangeKey1' ], ['hk2', 'rangeKey2'], ...], ...)
```

**Comment by cdhowie** [comment]
I don't recall if that is supported, but I know that an array of objects is supported:

```js
Model.getItems([
  { hashKey: 'value1', rangeKey: 'value2' },
  { hashKey: 'value3', rangeKey: 'value4'},
  ...
])
```
