### ISSUE TITLE
What is the best way to convert a list of objects 

### ISSUE THREAD

**Issue by digvijayy** [clarkie/dynogels#168]
dynogels returns attrs instead of plain JSON. I see that they get autoconverting when serializing or deserializing. What is the best way to convert them to plain JSON within the application?

**Comment by cdhowie** [comment]
The `get()` method of a document object will return the POD object behind it.  So, if you have done a query/scan and want to convert all of the response document objects into POD objects, you can just do:

```js
const podObjects = response.Items.map(i => i.get());
```
