### ISSUE TITLE
Model.validate not in latest release

### ISSUE THREAD

**Issue by stephentuso** [clarkie/dynogels#170]
Am I missing something? I see the PR (#110), and the [tests](https://github.com/clarkie/dynogels/blob/master/test/index-test.js#L62), but it doesn't look like the validate method is present. Here is a runkit showing the error, with the code directly copied from the docs: https://runkit.com/stephentuso/5c06c7b91471ec0012bb6f2b

EDIT: scratch that, I see latest release is Nov 2017 and that PR was merged in Dec. Will there be a new release soon?

**Comment by cdhowie** [comment]
I don't know if there will be a release. @clarkie appears to be busy with other projects or otherwise MIA. I'd suggest subscribing to #138.
