### ISSUE TITLE
confusing doc in delete items

### ISSUE THREAD

**Issue by tiant167** [clarkie/dynogels#18]
Hi,
```
You delete items in DynamoDB using the hashkey of model If your model uses both a hash and range key, than both need to be provided
```

than?  I think it should be `then` right?

```
You delete items in DynamoDB using the hashkey of model. If your model uses both a hash and range key, then both need to be provided
```

**Comment by clarkie** [comment]
@tiant167 thanks for letting me know. In future you can quickly submit PRs for documentation changes by editing the file on the main repository. Github will automatically fork the repo and then take you through the PR submission.
