### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by rchl** [clarkie/dynogels#180]
Given that autor didn't respond for over a year, I think the only sensible solution is to fork the project and integrate some much needed PRs.

I can't volunteer much time to it myself but hopefully someone will.

I propose new name - dynogelsNext

**Comment by cdhowie** [comment]
I have commit access but I don't believe I have the required keys to publish new versions to npm.

**Comment by thomasruiz** [comment]
@clarkie ?

**Comment by diosney** [comment]
Bump.

It is a shame that this project goes to waste, by only reading the README it can be seen that is huge and very useful, but it is too dangerous to use a stalled project :/

**Comment by cdhowie** [comment]
@diosney It could be forked... dynogels itself is a fork of vogels, which itself died.

But I would prefer if @clarkie could come back to at least hand over the reins, instead of having to change the name of the project a second time.  😞

**Comment by diosney** [comment]
@clarkie Agree completely.

**Comment by snamoah** [comment]
created a new project based on this and [dynogels-promisified](https://www.npmjs.com/package/dynogels-promisified). you can check it out here https://www.npmjs.com/package/dynogels-promise.  I updated the dependencies and made some few changes but you can replace it with either packges, and it should work perfectly

**Comment by clarkie** [comment]
Yo, apologies for going a bit off the grid. I've completely stopped using dynamodb (for now).

I'm happy for this to be moved over to a group/org type thing. What needs to happen to get this set up? I've got some time over the next few weeks where I should be able to hand this over to whoever wants to carry on maintaining it. 

I think there's two bits to do, github and npm. Anything else?

**Comment by cdhowie** [comment]
> I think there's two bits to do, github and npm. Anything else?

Probably the CI stuff as well.  If the integration tests hit a real DynamoDB then we have to figure out what to do with that AWS account.

**Comment by clarkie** [comment]
If I remember correctly the CI spins up a "local" dynamodb to run against

**Comment by cdhowie** [comment]
Cool, so in that case just access to the CI backend is an additional piece that would have to transition.

**Comment by MaximusHaximus** [comment]
I'd like to volunteer to help get V10 landed and help out with getting things converted to an org if needed.  Have been using dynogels for 3 years and would like the chance to give back :) @cdhowie @clarkie

**Comment by Tombmyst** [comment]
Any news on project update? I'm currently working on updating it and re-writing it in Typescript

**Comment by clarkie** [comment]
Sorry! What's the best structure for the new group? Is it a github org *and* an npm org? I've never set up an npm org before.

**Comment by snamoah** [comment]
Creating an organisation on npm is quite straightforward... the organisation structure on github is fine.. we can still keep `dynogels` name the same on npm imo

**Comment by jascination** [comment]
Any movement on this? @clarkie

**Comment by ErikBoesen** [comment]
https://docs.npmjs.com/creating-an-org
This is how you make an npm org. There are some vulnerabilities in this package's dependencies so it would be nice to get new maintainers access to upload there.

**Comment by nolde** [comment]
We really need to get this going. I am willing to help.

I am already thinking of creating yet another fork to cater to my business needs. I would rather do a PR for dynogels.

**Comment by clarkie** [comment]
Thanks @ErikBoesen I've created the npm org now I just need to invite @cdhowie in. Can you ping me your email or npm username.

**Comment by clarkie** [comment]
This will still move the npm dependency though right? So we'll get from `yarn add dynogels` to `yarn add @dynogels/core` or something similar?

**Comment by clarkie** [comment]
Oh hang on, we don't need to do all this. I can just add maintainers to the existing npm package. 

I still need @cdhowie's (and anyone else who y'all think should have publish rights) npm usernames

**Comment by ErikBoesen** [comment]
I agree that it would be preferable to just add maintainers.

**Comment by cdhowie** [comment]
@clarkie My username is the same over there. :)

**Comment by nolde** [comment]
Any news?

**Comment by clarkie** [comment]
I've added @zolaemil and @cdhowie as maintainers on npm

**Comment by zolaemil** [comment]
Thanks @clarkie!

**Comment by zolaemil** [comment]
I've now merged https://github.com/clarkie/dynogels/pull/155 and https://github.com/clarkie/dynogels/pull/179 and going to publish a release to npm with these soon.

**Comment by zolaemil** [comment]
I realise that `master` has some breaking changes since `v9.0.0`, so in order to move forward quickly with addressing vulnerabilities, I've decided to port these dependency updates back to v9 and make a release from there. 

https://github.com/clarkie/dynogels/releases/tag/v9.1.0
