### ISSUE TITLE
Add etag support

### ISSUE THREAD

**Issue by mwawrusch** [clarkie/dynogels#21]
It would be nice to automatically create an etag field (_etag) similar to the timestamps, based on the contents of the document (https://www.npmjs.com/package/etag). Might be a bit complicated for updates as it would require a read first though.

**Comment by clarkie** [comment]
Could you add some details as to how you'd expect this to work? 

My gut feeling is that storing an etag along with the body would not be right as that would then invalidate the etag. If you want it generated on the fly on reads then I'd say that isn't the concern of this library and should be handled by your web framework layer (e.g. hapi, express, etc.)

**Comment by clarkie** [comment]
Closing due to lack of update
