### ISSUE TITLE
Provide way to validate object/model without storing

### ISSUE THREAD

**Issue by cdhowie** [clarkie/dynogels#24]
It can be helpful, when performing writes across multiple tables, to validate all of the documents being saved against the tables' Joi schemas prior to beginning any of the writes.  This way, if any of the objects aren't valid according to the respective schema, none of the writes are attempted.

This functionality doesn't currently seem to be exposed; the only way to trigger a schema validation is to save the document.

**Comment by clarkie** [comment]
Good idea. 

I think I saw a workaround but I can't find it now. I'm sure there was a conversation somewhere, either here or on vogels.

**Comment by cdhowie** [comment]
The main issue with this currently is that there doesn't seem to be any way to obtain the Joi schema object from a defined model.  (Created [here](https://github.com/clarkie/dynogels/blob/master/lib/index.js#L76), there's no path to the schema object.)  So to enable a workaround, I have to expose the schema object myself, for example:

```
const _ = require('lodash');
const dynogels = require('dynogels');

let define = dynogels.define.bind(dynogels);

dynogels.define = (name, def) =>
    _.set(define(name, def), 'schema', def.schema);
```

**Comment by cdhowie** [comment]
One thing I forgot is that the table object is reachable from items.  So what I ask is actually already possible (code is untested but the basic idea works):

```
'use strict';                                                  
                                                               
const _ = require('lodash');                                   
const Q = require('q');
                                                               
function validateAndSaveGels(models) {                         
    return Q.all(                                              
        _.map(models, m =>                                     
            Q.ninvoke(m.table.schema, 'validate', m.get())     
            .thenResolve(m)                                    
        )                                                      
    )
    .then(models =>                                            
        Q.all(_.map(m => m.save()))                            
    );                                                         
}                                                              
                                                               
module.exports = validateAndSaveGels;                          
```

Called like:

```
validateAndSaveGels([
    new dynogels.models.Foo({ ... }),
    new dynogels.models.Bar({ ... })
])
.then(...);
```

**Comment by dangerginger** [comment]
I was just searching for a way to do this.  That is, I want to validate a model without trying to save it and seeing if it works or not.  Is this still a valid enhancement?  I am interested in sending a pull request if so.

**Comment by clarkie** [comment]
Yeah, definitely up for a PR. We keep all our dynogels interactions in separate files anyway and export the schemas from there anyway.

**Comment by dangerginger** [comment]
Ok.  I started looking at this briefly and didn't immediately understand where the schema was stored.  It doesn't seem to be a property of model instances and I couldn't figure out how to grab it from the model definition either.  Do you know offhand where to get started on this?

**Comment by clarkie** [comment]
Not really to be honest, I think this is where I'd start: https://github.com/clarkie/dynogels/blob/master/lib/table.js#L15

Thanks!

**Comment by cdhowie** [comment]
@dangerginger If you have a model object `m`, the schema is at `m.table.schema`.

**Comment by dangerginger** [comment]
Thanks @cdhowie.  I will look into this and hopefully submit a PR over the weekend.

**Comment by dangerginger** [comment]
@cdhowie Check out #110 and let me know what you think.

**Comment by cdhowie** [comment]
@dangerginger Looks good to me

**Comment by dangerginger** [comment]
Fixed by #110

**Comment by Dombo** [comment]
Just a heads up - I have pulled v9.0.0 and it does not include these changes.

```
dynogels@^9.0.0:
  version "9.0.0"
  resolved "https://registry.yarnpkg.com/dynogels/-/dynogels-9.0.0.tgz#cb863764647dfd027afeb9be20bc5082423d5125"
  integrity sha1-y4Y3ZGR9/QJ6/rm+ILxQgkI9USU=
  dependencies:
    async "2.5.0"
    aws-sdk "2.131.0"
    joi "11.3.4"
    lodash "4.17.4"
    uuid "3.1.0"
```

**Comment by cdhowie** [comment]
@Dombo 9.0.0 was released in November 2017, and this change was committed in December 2017.
