### ISSUE TITLE
Joi.date in Joi.array.items issue

### ISSUE THREAD

**Issue by javatask** [clarkie/dynogels#26]
Strange issue: 
when I post 
object-pois-
{
...
valid-from:"2016-09-23"
valid-until:"2016-09-17"
}

to schema with array of pois with date fields - NO values of valid-from and valid-until where saved

Schema is
`import {
  types
} from 'dynogels';
import Joi from 'joi';

const location = {
  'lat': Joi.number(),
  'long': Joi.number()
}

const address = {
  'street': Joi.string(),
  'city': Joi.string(),
  'state': Joi.string(),
  'zip': Joi.string(),
}

const poi = {
  'id': types.uuid(),
  'name': Joi.string(),
  'location': location,
  'address': address,
  'phone': Joi.string(),
  'category': Joi.string(),
  'details': Joi.string().max(500),
  **'valid-from': Joi.date(),
  'valid-until': Joi.date()**
}

export default {
  hashKey: 'mapId',

  // add the timestamp attributes (updatedAt, createdAt)
  timestamps: true,

  schema: {
    'mapId': types.uuid(),
    'name': Joi.string().required(),
    'folder': Joi.string().required(),
    'icon-url': Joi.string().uri(),
    'map-url': Joi.string().uri(),
    'map-size': Joi.number().positive(),
    'area-coordinates': {
      'from': location,
      'to': location
    },
    'pois': Joi.array().items(poi).sparse(true),
    'price': Joi.number(),
    'access': Joi.any().valid([0, 1, 2, 3]).required(),
    'valid-from': Joi.date(),
    'valid-until': Joi.date()
  }
};
`

**Comment by cdhowie** [comment]
I think this is a duplicate of #22.

**Comment by javatask** [comment]
Dublicate of #22
