### ISSUE TITLE
prevent overwriting based on global secondary index

### ISSUE THREAD

**Issue by edupre** [clarkie/dynogels#31]
Hello,
My understanding is that `{overwrite : false}` prevents overwriting only based on the partition key.

When I create an object with a generated partition key (uuid), how can I prevent overwriting based on another attribute (for instance, an email address) ? Note that this attribute could be a global secondary index.

Thanks!

**Comment by clarkie** [comment]
Unfortunately this isn't realistic with DynamoDB. The best approach is to use the email address as the hashkey. This is the only way to guarantee uniqueness with dynamodb.

**Comment by clarkie** [comment]
For more information on conditional writes please see #32
