### ISSUE TITLE
dynogels.types.uuid() returning an Object

### ISSUE THREAD

**Issue by charlesnoble** [clarkie/dynogels#36]
Reinstalled my node_modules folder for the first time in 17 days and suddenly dynogels.types.uuid() is not returning a UUID, but returning an Object for some strange reason.

I kept receiving the error:

```
error: 'child "id" fails because ["id" must be a string] on ...
```

and on further investigation, id looked like:

```
     id: 
      { '0': 46,
        '1': 122,
        '2': 34,
        '3': 227,
        '4': 36,
        '5': 212,
        '6': 68,
        '7': 24,
        '8': 164,
        '9': 166,
        '10': 226,
        '11': 139,
        '12': 86,
        '13': 61,
        '14': 108,
        '15': 195,
        abortEarly: false,
        convert: true,
        allowUnknown: false,
        skipFunctions: false,
        stripUnknown: false,
        language: {},
        presence: 'optional',
        strip: false,
        noDefaults: false },
```

and my schema file looks like:

```
var schema = {
  id: dynogels.types.uuid(),
```

Not sure where this has come from and nothing else has changed and it was all previously working very well.

Thanks for the help! :+1:

**Comment by clarkie** [comment]
Hi, can you post your `package.json` file please? What version of Joi and Dynogels are you using?

**Comment by charlesnoble** [comment]
Wow, straight on it, great work!

package.json:
```
  "dependencies": {
    "async": "^2.0.0",
    "aws-sdk": "2.4.8",
    "babel-core": "^6.11.4",
    "babel-preset-es2017": "^1.4.0",
    "baidumap": "0.0.3",
    "body-parser": "^1.15.2",
    "bwip-js": "^1.0.5",
    "chance": "^1.0.4",
    "cheerio": "^0.22.0",
    "connect-busboy": "0.0.2",
    "connect-dynamodb": "^1.0.8",
    "cors": "^2.7.1",
    "debug": "^2.2.0",
    "deep-extend": "^0.4.1",
    "direct-alipay": "github:charlesnoble/direct-alipay",
    "dynogels": "^5.0.2",
    "express": "^5.0.0-alpha.2",
    "express-session-query": "github:alex0007/session",
    "extend-or-modify": "^1.0.0",
    "gc-auto": "^0.3.1",
    "geolib": "^2.0.21",
    "google-spreadsheet": "^2.0.3",
    "html-pdf": "^2.0.1",
    "humps": "^1.1.0",
    "i18n-iso-countries": "^1.2.1",
    "joi": "^9.0.1",
    "jszip": "^3.0.0",
    "key-del": "^1.2.4",
    "lodash": "^4.13.1",
    "mailgun-js": "^0.7.11",
    "moment": "^2.14.1",
    "morgan": "^1.7.0",
    "node-geocoder": "^3.13.0",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "pdfkit": "^0.7.2",
    "pluralize": "^3.0.0",
    "pmx": "^0.6.2",
    "pug": "^2.0.0-beta4",
    "raw-body": "^2.1.7",
    "require-dir": "^0.3.0",
    "rx": "^4.1.0",
    "shortid": "^2.2.6",
    "stripe": "^4.9.0",
    "xlsx": "^0.8.0",
    "xto": "^1.1.7"
  },
```
I tried updating both Joi and Dynogels, but the same issue.

**Comment by cdhowie** [comment]
The object shown looks suspiciously like the Joi options object.  Can you post an [MCVE](http://stackoverflow.com/help/mcve) of the issue?

I can't reproduce the behavior on my end; the type works as I would expect:

```js
> require('.').types.uuid().validate();
{ error: null, value: '1c6102e1-b896-434e-a9f1-66d7016bc732' }
```

**Comment by charlesnoble** [comment]
I can reproduce those results too:

```
  let test = dynogels.types.uuid().validate();
  console.log(test)
```
Outputs:

{ error: null, value: '421ea917-c879-4d43-9d6b-ee1d72c11a22' }

I'll investigate more today and see what I can find.

**Comment by charlesnoble** [comment]
Temporarily I've implemented:

```
import { generateUUID } from '../utils/short-hash'

var schema = {
  id: Joi.string().guid().default(generateUUID),
```

and in short-hash.js:

```
import nodeUUID from 'node-uuid'

export let generateUUID = (context) => {
    return nodeUUID.v4()
}

generateUUID.description = 'uuid v4'
```

That seems to be working. I'll try to continue debugging the other issue later tomorrow.

**Comment by Si1kIfY** [comment]
Can reproduce this too on my end from a new install

package.json
```
    "dynogels": "^6.1.0",
    "joi": "^9.2.0",
```

Any version number I can drop to for the moment?

**Comment by dylanswartz** [comment]
Just started having this issue as well on a number of my services: 
```
"dynogels": "^5.1.0",
"joi": "^9.0.4",
```
Looks like joi 9.2.0 gets installed. Locked it into 9.0.4 for a fix.

**Comment by clarkie** [comment]
you're right, this seems to break the tests too. 
`npm i joi@9.0 && npm t` ✅ 
`npm i joi@9.1 && npm t` ❌ 
`npm i joi@9.2 && npm t` ❌ 
I'm looking into what changed in 9.1

**Comment by clarkie** [comment]
Thanks for your help with this, I've raised an issue asking for help from the `joi` lot.
