### ISSUE TITLE
allow index scan

### ISSUE THREAD

**Issue by stevenao** [clarkie/dynogels#42]
the feature was added a few months ago in dynamodb. Can you add it to the scan module? currently, i manually add it to the scan prototype. 

`require('dynogels/lib/scan').prototype.usingIndex = function (name) {
    this.request.IndexName = name;
    return this;
  };
`

**Comment by M1chaelTran** [comment]
+1

**Comment by dangerginger** [comment]
Let's reopen this if there is some more activity here.  Might not take too much effort to do a patch if the functionality is similar to the `.usingIndex()` method for `.query()`.

**Comment by thomasruiz** [comment]
@dangerginger It'd be nice to have this. Currently we have dirty checks whether to use query or scan, leading to some complexity overall.
