### ISSUE TITLE
Allow more than 5 concurrent index creation

### ISSUE THREAD

**Issue by M1chaelTran** [clarkie/dynogels#47]
I noticed that we limit to 5 concurrent index creation at a given time https://github.com/clarkie/dynogels/blob/fd69d3758ce6a8b7cb17043f7be83ccff9302448/lib/table.js#L658
There's also a ticket on Vogels https://github.com/ryanfitz/vogels/issues/125 for this issue

It used to be a limitation by AWS Dynamodb, but not anymore!
Would love some help to correct remove this limitation.

**Comment by dangerginger** [comment]
I'm going to close this for now.  If you are still interested in this issue let me know.

**Comment by cdhowie** [comment]
This is [still a limitation](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html), from what I can see.

> In general, you can have up to 10 `CreateTable`, `UpdateTable`, and `DeleteTable` requests running simultaneously (in any combination). In other words, the total number of tables in the `CREATING`, `UPDATING` or `DELETING` state cannot exceed 10.
>
> The only exception is when you are creating a table with one or more secondary indexes. You can have up to 5 such requests running at a time; however, if the table or index specifications are complex, DynamoDB might temporarily reduce the number of concurrent requests below 5.
