### ISSUE TITLE
.update() will create new items

### ISSUE THREAD

**Issue by dangerginger** [clarkie/dynogels#51]
This was brought up in #39, but is separate from the main issue there which is schema enforcement.  Basically, you can create a new item in DynamoDB with an update call.  The expected behavior should be to fail and only allow creating new items with a call to .create().

**Comment by deedw** [comment]
See comments against pull request #50. I believe existing functionality is as expected for DynamoDb and changes to this would break existing code.

**Comment by dangerginger** [comment]
I updated the documentation in #53.  This provides an easy way to modify the behavior of update to fail for items that don't exist.  In fact, this was an undocumented feature already in the code.  I added two tests to check the behavior works and described the parameter in the README.md.
