### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by AaronHarris** [clarkie/dynogels#56]
I've finally accepted reality and moved over to using dynogels going forward. However seeing as this module is more actively maintained (with several of major version bumps), it would be super helpful for those migrating from vogels to be able to see what changes they may need to make to their existing vogels-based code, without having to go through each commit since the fork. This has improved in the more recent releases, but many of the older releases just contain the version number bump along with dozens of commits, and isn't really a single place to see what's changed since Vogels.

This may not be sustainable indefinitely, but until a majority of vogels users transition to dynogels, I think it might help speed up adoption. I've started going through some of the new commits/releases myself, but thought this would be a more accurate and probably easier if done by one of the contributors / maintainers.

Thanks for all the work you've done @clarkie, et al in the past year!

**Comment by clarkie** [comment]
Hi, thanks for your suggestion. I'd be happy to have something automatic but for now I've been using githubs 'releases/tags' thing: https://github.com/clarkie/dynogels/releases

Is this good enough for now or can you recommend something else?

**Comment by clarkie** [comment]
Closing but happy to reopen if we have some new ideas.
