### ISSUE TITLE
Support for new aws-sd dynamodb driver feature: convert empty values to null

### ISSUE THREAD

**Issue by endymion00** [clarkie/dynogels#64]
"Converting empty values to null is now an opt-in feature of the document client; you can pass a boolean `convertEmptyValues` option to the document client constructor to have it do so."

See https://github.com/aws/aws-sdk-js/issues/833

**Comment by igorhmm** [comment]
+1

**Comment by dangerginger** [comment]
Dynogels does not support null values, as setting an attribute to null is used to delete the attribute from the model.

**Comment by kernwig** [comment]
Note that this fails if the attribute is part of a secondary index. `undefined` would have been a better choice.
