### ISSUE TITLE
Pure-JS logging package?

### ISSUE THREAD

**Issue by focusaurus** [clarkie/dynogels#65]
I'm a bit frustrated with bunyan as it uses native add-ons. At the moment the pain this causes me is frequent needs for `npm rebuild` when I switch between node v4 (for AWS lambda) and node v6 (where debugging works well). I also just find it annoying when there are native modules without a really compelling reason, and I don't think logging records to stdout justifies native add-ons. I have no need for the D-trace baggage bunyan brings along with it.

Just starting this issue to see if anyone else is motivated to maybe swap in `bole`.

**Comment by clarkie** [comment]
I'd be interested in a PR that removes the logging completely and allows you to just pass in whatever logging you want. I very rarely use the logging anyway.

**Comment by focusaurus** [comment]
OK I'll take a crack at that.

**Comment by clarkie** [comment]
@focusaurus can you have a look at #84 thanks
