### ISSUE TITLE
Question: Pagination caps?

### ISSUE THREAD

**Issue by ccverak** [clarkie/dynogels#66]
Is it possible to get LastEvauatedKey and pass it to queries to perform forward pagination?

**Comment by sid88in** [comment]
hey @ccverak did you figure this out? I am trying to understand pagination in dynamodb as well. https://forums.aws.amazon.com/thread.jspa?threadID=262177&tstart=0

**Comment by cdhowie** [comment]
@ccverak The object returned from query/scan operations includes `LastEvaluatedKey` alongside `Items`, but I don't think query/scan provides an API to provide this value.

Honestly, pagination should just be something we provide as a method on the returned object.  There's no reason for developers to have to deal with directly passing that value around.

**Comment by apalaniuk** [comment]
Does `startKey()` not provide this?

**Comment by cdhowie** [comment]
You are right, I missed that when scanning the source code.  In that case, there's nothing to do here.  (Though I would like to add a `next()` method to the result object that will encapsulate this logic.)

**Comment by iDVB** [comment]
Does `startKey()` completely solve this? 
Just thinking about this now. Does this not mean the frontend needs to track all keys, in order to know which is the first of a block of say 20?

Example: What if a user goes directly to this link `domain.com/search?page=3&pagesize=10`

How would the front end know what `startkey()` to send if they want to go back a single page?

**Comment by cdhowie** [comment]
On February 2, 2018 4:41:28 PM UTC, Dan Van Brunt <notifications@github.com> wrote:
>Does `startKey()` completely solve this? 
>Just thinking about this now. Does this not mean the frontend needs to
>track all keys, in order to know which is the first of a block of say
>20?
>
>Example: What if a user goes directly to this link
>`domain.com/search?page=3&pagesize=10`
>
>How would the front end know what `startkey()` to send if they want to
>go back a single page?

Dynamo doesn't support offsets. The proper way to implement this would be to pass the start key instead of a numeric offset.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by iDVB** [comment]
@cdhowie Ya I think my disconnect here was that from an architecture point of view, DynamoDB itself is not the type of DB to handle backward paging lookups like this. We're getting around this by using  ElasticSearch for things like this. 

So naturally any ORM is not going to correct the underlining arch consideration.

**Comment by cdhowie** [comment]
Right.  Any workaround would be something at the application level, not the ORM.  (Though dynogels isn't even an ORM, it's just an OM.)
