### ISSUE TITLE
Drop joi dependency in favor of json schema/ajv.  PR accepted?

### ISSUE THREAD

**Issue by cmawhorter** [clarkie/dynogels#67]
As someone that is using dynogels heavily in lambda;  Joi -- and anything hapijs -- is the bane of my existence.  

Joi alone turns my lambda 850kb bundle.zip into 3mb.  And because their community violently opposes bundlers, they've stated time and time again they DGAF about making it better.  

(I also [question the security](http://imgur.com/a/DHZJY) when this stuff goes unfixed even after reporting. Everything in a few of hapijs projects is globally +x for some unknown reason.)

Is there any interest in a PR that drops Joi and replaces it with json schema and something like [ajv](https://github.com/epoberezkin/ajv)?

JSON Schema is not without its quirks, but it's a standard that works everywhere.  Also -- aws seems to be choosing it internally with their api gateway swagger support and other places.

**Comment by iliasbhal** [comment]
+1  !!!

**Comment by nielsgl** [comment]
@cmawhorter definitely would like to see that, have you implemented it in a fork?

**Comment by clarkie** [comment]
I haven't got the time to look at this but I'd be happy to have a look at a fork that does. Closing for now.
