### ISSUE TITLE
Table name is wrong when it is pluralized.

### ISSUE THREAD

**Issue by rahulkulmi** [clarkie/dynogels#70]
Table name is not pluralized  properly when model name end with "y" like that 
category is become categorys which is wrong it will become categories. So please consider it is a bug and fix this in next reales.

**Comment by M1chaelTran** [comment]
this issue has been raised #48 

My current work around is using the `tableName` property.

**Comment by rahulkulmi** [comment]
@M1chaelTran Thanks for reply.
