### ISSUE TITLE
Allow null properties on nested data

### ISSUE THREAD

**Issue by diit** [clarkie/dynogels#93]
## Expected
Sending a null value to a nested property results in it being deleted. Should be consistent with root level schema.

## Result
Dynogel throws validation error.

## Current solution
appending every value in nested schema with ```.allow(null)```

**Comment by clarkie** [comment]
Thanks @diit, I probably haven't got time at the minute to do this but if you wanted to submit a PR or create a branch with some failing tests that'd be a great start.

Thanks

**Comment by dangerginger** [comment]
Setting a property to a null value deletes that property in dynogels, according to the README.md.  This it is consistent with the root level properties in the schema.  Although dynamodb now allows null values, dynogels uses a null value assignment to indicate the property should be removed.
