### ISSUE TITLE
is OR operator planned?

### ISSUE THREAD

**Issue by mvayngrib** [clarkie/dynogels#95]
first off, awesome library, very useful!

I noticed that the OR operator is not implemented (unless i missed something). Is it planned / is there a discussion about it somewhere?

**Comment by clarkie** [comment]
@mvayngrib I don't really have any plans to add anything else to dynogels at the minute as it's doing everything we need at Tido but I'm always up for PRs if you think it will add to the library.

**Comment by mvayngrib** [comment]
@clarkie fair enough, I may send a PR in the future. At the moment I'm ok without it :)

**Comment by sp90** [comment]
Has this been put in after this discussion?
