### ISSUE TITLE
Difference b/w creating one doc vs multiple

### ISSUE THREAD

**Issue by tarunbatra** [clarkie/dynogels#98]
`Model.create` can take either one doc or an array of them. I'm curious if giving an array at once will likely cross the provisioned capacity of the DynamoDB table (assuming it's very low), or dynogels does some kind of throttling?

**Comment by clarkie** [comment]
Dynogels doesn't do any throttling of batch requests. The AWS-SDK does have automatic retrying if you exceed your provisioned throughput. 

> ProvisionedThroughputExceededException

> Message: You exceeded your maximum allowed provisioned throughput for a table or for one or more global secondary indexes. To view performance metrics for provisioned throughput vs. consumed throughput, open the Amazon CloudWatch console.

> Example: Your request rate is too high. The AWS SDKs for DynamoDB automatically retry requests that receive this exception. Your request is eventually successful, unless your retry queue is too large to finish. Reduce the frequency of requests, using Error Retries and Exponential Backoff.

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.MessagesAndCodes

I hope that helps.
